-- MySQL Script generated by MySQL Workbench
-- 05/07/18 14:53:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`UserRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UserRole` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UserRole` (
  `idUserRole` INT NOT NULL AUTO_INCREMENT,
  `UserRolecol` VARCHAR(15) NULL,
  PRIMARY KEY (`idUserRole`),
  UNIQUE INDEX `idUserRole_UNIQUE` (`idUserRole` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `usrSurame` VARCHAR(50) NULL,
  `usrName` VARCHAR(50) NULL,
  `usrAddress` VARCHAR(50) NULL,
  `usrNPA` VARCHAR(10) NULL,
  `usrlieu` VARCHAR(60) NULL,
  `usrPassword` VARCHAR(100) NULL,
  `UserRole_idUserRole` INT NOT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `idUtilisateurs_UNIQUE` (`idUsers` ASC),
  INDEX `fk_Users_UserRole_idx` (`UserRole_idUserRole` ASC),
  CONSTRAINT `fk_Users_UserRole`
    FOREIGN KEY (`UserRole_idUserRole`)
    REFERENCES `mydb`.`UserRole` (`idUserRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Statut`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Statut` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Statut` (
  `idStatut` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(10) NULL,
  `Motif` VARCHAR(150) NULL,
  PRIMARY KEY (`idStatut`),
  UNIQUE INDEX `idStatut_UNIQUE` (`idStatut` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contract` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contract` (
  `idContract` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(150) NULL,
  `BeginDate` DATE NULL,
  `EndDate` VARCHAR(45) NULL,
  `Statut_idStatut` INT NOT NULL,
  `Users_idUsers` INT NOT NULL,
  PRIMARY KEY (`idContract`),
  UNIQUE INDEX `idContract_UNIQUE` (`idContract` ASC),
  INDEX `fk_Contract_Statut1_idx` (`Statut_idStatut` ASC),
  INDEX `fk_Contract_Users1_idx` (`Users_idUsers` ASC),
  CONSTRAINT `fk_Contract_Statut1`
    FOREIGN KEY (`Statut_idStatut`)
    REFERENCES `mydb`.`Statut` (`idStatut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contract_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CubeSat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CubeSat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CubeSat` (
  `idCubeSat` INT NOT NULL AUTO_INCREMENT,
  `csName` VARCHAR(45) NULL,
  `csMass` FLOAT NULL,
  `csPrice` FLOAT NULL,
  `SolarPanel` TINYINT(1) NULL,
  `Height` INT NULL,
  `Width` INT NULL,
  `Length` INT NULL,
  `BatterySpace` INT NULL,
  `Stock` INT NULL,
  `Description` VARCHAR(150) NULL,
  PRIMARY KEY (`idCubeSat`),
  UNIQUE INDEX `idCubeSat_UNIQUE` (`idCubeSat` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Extensions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Extensions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Extensions` (
  `idExtensions` INT NOT NULL AUTO_INCREMENT,
  `extDescription` VARCHAR(150) NULL,
  `Manufacturer` VARCHAR(45) NULL,
  `extType` VARCHAR(45) NULL,
  `extName` VARCHAR(45) NULL,
  `extMass` FLOAT NULL,
  `extPrice` FLOAT NULL,
  `extStock` INT NULL,
  PRIMARY KEY (`idExtensions`),
  UNIQUE INDEX `idExtensions_UNIQUE` (`idExtensions` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Battery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Battery` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Battery` (
  `idBattery` INT NOT NULL AUTO_INCREMENT,
  `BatterySpace` INT NULL,
  `Capacity` FLOAT NULL,
  `ChargingVoltage` FLOAT NULL,
  `Description` VARCHAR(45) NULL,
  `Stock` INT NULL,
  PRIMARY KEY (`idBattery`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CubeSat_has_Extensions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CubeSat_has_Extensions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CubeSat_has_Extensions` (
  `CubeSat_idCubeSat` INT NOT NULL,
  `Extensions_idExtensions` INT NOT NULL,
  PRIMARY KEY (`CubeSat_idCubeSat`, `Extensions_idExtensions`),
  INDEX `fk_CubeSat_has_Extensions_Extensions1_idx` (`Extensions_idExtensions` ASC),
  INDEX `fk_CubeSat_has_Extensions_CubeSat1_idx` (`CubeSat_idCubeSat` ASC),
  CONSTRAINT `fk_CubeSat_has_Extensions_CubeSat1`
    FOREIGN KEY (`CubeSat_idCubeSat`)
    REFERENCES `mydb`.`CubeSat` (`idCubeSat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CubeSat_has_Extensions_Extensions1`
    FOREIGN KEY (`Extensions_idExtensions`)
    REFERENCES `mydb`.`Extensions` (`idExtensions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CubeSat_has_Contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CubeSat_has_Contract` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CubeSat_has_Contract` (
  `CubeSat_idCubeSat` INT NOT NULL,
  `Contract_idContract` INT NOT NULL,
  PRIMARY KEY (`CubeSat_idCubeSat`, `Contract_idContract`),
  INDEX `fk_CubeSat_has_Contract_Contract1_idx` (`Contract_idContract` ASC),
  INDEX `fk_CubeSat_has_Contract_CubeSat1_idx` (`CubeSat_idCubeSat` ASC),
  CONSTRAINT `fk_CubeSat_has_Contract_CubeSat1`
    FOREIGN KEY (`CubeSat_idCubeSat`)
    REFERENCES `mydb`.`CubeSat` (`idCubeSat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CubeSat_has_Contract_Contract1`
    FOREIGN KEY (`Contract_idContract`)
    REFERENCES `mydb`.`Contract` (`idContract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Battery_has_CubeSat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Battery_has_CubeSat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Battery_has_CubeSat` (
  `Battery_idBattery` INT NOT NULL,
  `CubeSat_idCubeSat` INT NOT NULL,
  PRIMARY KEY (`Battery_idBattery`, `CubeSat_idCubeSat`),
  INDEX `fk_Battery_has_CubeSat_CubeSat1_idx` (`CubeSat_idCubeSat` ASC),
  INDEX `fk_Battery_has_CubeSat_Battery1_idx` (`Battery_idBattery` ASC),
  CONSTRAINT `fk_Battery_has_CubeSat_Battery1`
    FOREIGN KEY (`Battery_idBattery`)
    REFERENCES `mydb`.`Battery` (`idBattery`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Battery_has_CubeSat_CubeSat1`
    FOREIGN KEY (`CubeSat_idCubeSat`)
    REFERENCES `mydb`.`CubeSat` (`idCubeSat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
